image: Visual Studio 2017

cache:
  - packages -> **\packages.config

before_build:
  - ps: sqllocaldb c "v13.0" 13.0 -s

build_script:
  - ./build.cmd /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

test: off

artifacts:
  - path: ./msbuild.log
  - path: ./artifacts/*.nupkg

deploy:
  - provider: Environment
    name: NuGet
    on:
      branch: master
